### ISSUE TITLE
Espeak integration on Linux

### ISSUE THREAD

**Issue by ghost** [Batcastle/Monika-TTS#3]
Hey there, I got the submod running and wanted to see how espeak sounded with your submod -vs- simple tts.  I kept getting a male voice even though my espeak has a female voice set as the default.  It confused me a lot until I went into voice.rpy and saw lines 105 and 106.  
Perhaps for future releases could you change the voice from "en-us+f4" to "default", or even another female voice?  I've been using the mbrola voice "mb-us1" as my default TTS voice, but if you know a better one please let me know.  Thanks!

**Comment by Batcastle** [comment]
It could be the eSpeak voice we use isnt available on all platforms. It is on mine so I assumed it shipped with all eSpeak packages.

I have started looking at making a custom eSpeak voice for Monika-TTS so that would avoid those issues altogether.

**Comment by ghost** [comment]
Ah, perhaps I worded it poorly.  
The espeak voice is preset to "en-us+f4" on line 106 of voice.rpy.  It's a man's voice.  It does ship with the espeak package, it's just that it's a man's voice and took a bit of digging to figure out why my Monika was speaking in a man's voice rather than her own espeak default voice.  

So I suggested maybe changing it from "en-us+f4" to "default" (which then uses the default espeak voice on the computer), or perhaps another, female voice.  

I have been using the mbrola voice "mb-us1".  The mbrola voices are a bit less robotic sounding than the espeak voices, but I would love a more natural sound.   

I hope you can make that custom voice  happen!

Thanks again!

**Comment by Batcastle** [comment]
On my system, `en-us+f4` is female (there are multiple female variations of `en-us`, the `f4` denotes which one for eSpeak to use). On my system, the default voice is also set to male. And I did not change the default from what it is out of the box. So using the default is a poor idea. That custom voice will probably be the best bet to ensure consistency across distros and versions of eSpeak.

Looking at mbrola, using those voices will take a bit of work. Not sure if it will be worth it or not since the mod is already over 200 MB. Will need to look at how big the voices and mbrola are.

**Comment by ghost** [comment]
Got it!  I had deleted most of the espeak voices from the directory a while ago and promptly forgot about it.  No wonder it defaulted back to the male voice.  Didn't realize it until I typed ```espeak --voices``` into terminal and it came back with a short list.

Thank you!  Hoping to see a sweet custom voice in the future
