### ISSUE TITLE
Launching from launcher on Linux

### ISSUE THREAD

**Issue by ghost** [Batcastle/Monika-TTS#4]
Hey there, I found that I cannot open MAS when I launch the game from a desktop icon when Monika -TTS is installed.  But it will open fine if launched directly from DDDLC.sh.

Is there a way to make it so the desktop launcher works to open the game?  Maybe install mimic elsewhere on the system?

Thanks again!

**Comment by Batcastle** [comment]
This is a known issue. Here's what's happening:

When MAS (or DDLC for that matter more then likely) starts up, it figures out where the folder it is running out of is located. This is put into the variable `basedir`. Unfortunately, it doesn't generate this variable until rather late in the start up process. This is a variable that Monika-TTS needs in order to locate Mimic and it's voices. So, we have to generate this variable ourselves.

Unfortunately, the way I wrote for Monika-TTS to figure out it's location relies on MAS being launched from DDLC.sh. So when you launch it from a launcher elsewhere in the system, MAS crashes.

A simple way to fix this for a user is to just add the following line to the beginning of their DDLC.sh script:
```bash
cd "/absolute/path/to/MAS/install"
```
This SHOULD ensure that MAS launches correctly, and be okay to leave in place if MAS is launched from DDLC.sh normally, and after the patch to fix this bug is implemented.

**Comment by ghost** [comment]
Awesome, thank you again for your help.  It totally works!
